// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqxhjqgqeddfgwpcwiln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxeGhqcWdxZWRkZmd3cGN3aWxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2ODQ4NjQsImV4cCI6MjA2ODI2MDg2NH0.PT7zvEUcCtcD4joo3NzOFqFahuLf3yywOaX-eFA2DXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});